/* polish-db.js — dictionary seed. Format: pl|english|part of speech|category|example pl = example en
   Pronunciation is generated by polish-engine.js. Extend with: python tools/pl_fix.py db words.csv */
window.PL_DB_RAW = `
cześć|hi / bye (informal)|interj|Greetings|Cześć, jak się masz? = Hi, how are you?
dzień dobry|good morning / hello (formal)|phrase|Greetings|Dzień dobry, pani Anno. = Good morning, Ms Anna.
dobry wieczór|good evening|phrase|Greetings
dobranoc|good night|interj|Greetings
do widzenia|goodbye|phrase|Greetings|Do widzenia, do jutra! = Goodbye, see you tomorrow!
na razie|see you later|phrase|Greetings
dziękuję|thank you|verb|Politeness|Dziękuję bardzo! = Thank you very much!
proszę|please / here you are|verb|Politeness|Proszę bardzo. = You're welcome / here you go.
poproszę|I'd like (polite order)|verb|Politeness|Poproszę kawę. = I'd like a coffee.
przepraszam|sorry / excuse me|verb|Politeness|Przepraszam, gdzie jest toaleta? = Excuse me, where is the toilet?
tak|yes|adv|Basics
nie|no / not|adv|Basics|Nie rozumiem. = I don't understand.
może|maybe|adv|Basics
dobrze|well / OK|adv|Basics|Mam się dobrze. = I'm doing well.
źle|badly|adv|Basics
bardzo|very|adv|Basics
trochę|a little|adv|Basics|Mówię trochę po polsku. = I speak a little Polish.
rozumiem|I understand|verb|Basics
nie rozumiem|I don't understand|phrase|Basics
mówię|I speak|verb|Basics
ja|I|pron|Pronouns
ty|you (informal)|pron|Pronouns
on|he|pron|Pronouns
ona|she|pron|Pronouns
my|we|pron|Pronouns
wy|you (plural)|pron|Pronouns
oni|they (men/mixed)|pron|Pronouns
pan|Mr / sir / you (to a man)|noun|Pronouns
pani|Ms / madam / you (to a woman)|noun|Pronouns
jestem|I am|verb|Verbs|Jestem z Polski. = I am from Poland.
jest|is|verb|Verbs
mam|I have|verb|Verbs|Mam brata. = I have a brother.
chcę|I want|verb|Verbs|Chcę wodę. = I want water.
mogę|I can|verb|Verbs|Mogę usiąść? = May I sit?
muszę|I must|verb|Verbs
lubię|I like|verb|Verbs|Lubię kawę. = I like coffee.
idę|I go (on foot)|verb|Verbs
mieszkam|I live|verb|Verbs|Mieszkam w Warszawie. = I live in Warsaw.
pracuję|I work|verb|Verbs
jem|I eat|verb|Verbs
piję|I drink|verb|Verbs
wiem|I know|verb|Verbs
kupuję|I buy|verb|Verbs
płacę|I pay|verb|Verbs|Płacę kartą. = I pay by card.
otworzyć|to open|verb|Verbs
wypłacić|to withdraw (money)|verb|Verbs
kosztuje|it costs|verb|Verbs|Ile to kosztuje? = How much does it cost?
boli|it hurts|verb|Health|Boli mnie głowa. = My head hurts.
co|what|pron|Questions
kto|who|pron|Questions
gdzie|where|adv|Questions|Gdzie jest dworzec? = Where is the station?
kiedy|when|adv|Questions
jak|how|adv|Questions
dlaczego|why|adv|Questions
ile|how much / how many|adv|Questions
czy|question particle (yes/no)|part|Questions|Czy to jest daleko? = Is it far?
jeden|one|num|Numbers
dwa|two|num|Numbers
trzy|three|num|Numbers
cztery|four|num|Numbers
pięć|five|num|Numbers
sześć|six|num|Numbers
siedem|seven|num|Numbers
osiem|eight|num|Numbers
dziewięć|nine|num|Numbers
dziesięć|ten|num|Numbers
sto|hundred|num|Numbers
złoty|zloty (currency)|noun|Money
pieniądze|money|noun|Money
karta|card|noun|Money|Mam kartę. = I have a card.
konto|account|noun|Money|Chcę otworzyć konto. = I want to open an account.
bank|bank|noun|Money
bankomat|ATM|noun|Money
gotówka|cash|noun|Money
rachunek|bill / check|noun|Money|Poproszę rachunek. = The bill, please.
paszport|passport|noun|Money
adres|address|noun|Money
za darmo|free of charge|phrase|Money
tanio|cheap|adv|Money
drogo|expensive|adv|Money
woda|water|noun|Food|Poproszę wodę. = Water, please.
kawa|coffee|noun|Food
herbata|tea|noun|Food
mleko|milk|noun|Food
sok|juice|noun|Food
piwo|beer|noun|Food
wino|wine|noun|Food
chleb|bread|noun|Food
bułka|bread roll|noun|Food
masło|butter|noun|Food
ser|cheese|noun|Food
szynka|ham|noun|Food
jajko|egg|noun|Food
zupa|soup|noun|Food
mięso|meat|noun|Food
ryba|fish|noun|Food
kurczak|chicken|noun|Food
ziemniaki|potatoes|noun|Food
ryż|rice|noun|Food
jabłko|apple|noun|Food
ciastko|cookie / pastry|noun|Food
cukier|sugar|noun|Food
śniadanie|breakfast|noun|Food
obiad|lunch / dinner|noun|Food
kolacja|supper|noun|Food
smacznego|enjoy your meal|interj|Food
menu|menu|noun|Food
restauracja|restaurant|noun|Places
kawiarnia|café|noun|Places
sklep|shop|noun|Places|Idę do sklepu. = I'm going to the shop.
apteka|pharmacy|noun|Places
szpital|hospital|noun|Places
dworzec|station|noun|Places
przystanek|bus stop|noun|Places
lotnisko|airport|noun|Places
hotel|hotel|noun|Places
szkoła|school|noun|Places
toaleta|toilet|noun|Places
ulica|street|noun|Places
miasto|city|noun|Places
dom|house / home|noun|Places
mieszkanie|flat|noun|Places
prosto|straight|adv|Directions|Idź prosto. = Go straight.
w lewo|to the left|phrase|Directions
w prawo|to the right|phrase|Directions
blisko|near|adv|Directions
daleko|far|adv|Directions
tutaj|here|adv|Directions
tam|there|adv|Directions
autobus|bus|noun|Transport
pociąg|train|noun|Transport
tramwaj|tram|noun|Transport
taksówka|taxi|noun|Transport
bilet|ticket|noun|Transport|Poproszę bilet. = A ticket, please.
samochód|car|noun|Transport
rodzina|family|noun|People
mama|mum|noun|People
tata|dad|noun|People
brat|brother|noun|People
siostra|sister|noun|People
syn|son|noun|People
córka|daughter|noun|People
przyjaciel|friend (male)|noun|People
przyjaciółka|friend (female)|noun|People
dziecko|child|noun|People
mężczyzna|man|noun|People
kobieta|woman|noun|People
lekarz|doctor|noun|Health
głowa|head|noun|Body
gardło|throat|noun|Body
brzuch|stomach|noun|Body
ręka|hand / arm|noun|Body
noga|leg|noun|Body
ząb|tooth|noun|Body
chory|sick|adj|Health
zdrowy|healthy|adj|Health
leki|medicine|noun|Health
pomocy|help!|noun|Health
dzisiaj|today|adv|Time
jutro|tomorrow|adv|Time
wczoraj|yesterday|adv|Time
teraz|now|adv|Time
potem|then / later|adv|Time
rano|morning (in the)|adv|Time
wieczorem|in the evening|adv|Time
poniedziałek|Monday|noun|Time
wtorek|Tuesday|noun|Time
środa|Wednesday|noun|Time
czwartek|Thursday|noun|Time
piątek|Friday|noun|Time
sobota|Saturday|noun|Time
niedziela|Sunday|noun|Time
tydzień|week|noun|Time
godzina|hour|noun|Time
czerwony|red|adj|Colours
niebieski|blue|adj|Colours
zielony|green|adj|Colours
czarny|black|adj|Colours
biały|white|adj|Colours
duży|big|adj|Adjectives
mały|small|adj|Adjectives
nowy|new|adj|Adjectives
dobry|good|adj|Adjectives
zły|bad / angry|adj|Adjectives
ładny|pretty|adj|Adjectives
gorący|hot|adj|Adjectives
zimny|cold|adj|Adjectives
w|in|prep|Prepositions
na|on / at|prep|Prepositions
do|to / into|prep|Prepositions
z|with / from|prep|Prepositions
dla|for|prep|Prepositions
i|and|conj|Prepositions
ale|but|conj|Prepositions
lub|or|conj|Prepositions
`;
